package Interfaces;

/**
 *
 * @author Elie Abboud
 */
public class WelcomeFrame extends javax.swing.JFrame {
    
    /*static pour pouvoir appeler ce Frame et le fermer quand-t-on clique sur
    le bouton retour du NouvGrapheFrame*/
    public static DessinerFrame dessiner;
    
    /**
     * Creates new form WelcomeFrame
     */
    public WelcomeFrame() {
        initComponents();
        //to put the welcomeFrame in the center we use the JFrame method "setLocationRelativeTo(null)"
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NouveauGrapheBoutton = new javax.swing.JButton();
        RevenirMesGraphesBoutton = new javax.swing.JButton();
        MesGraphesBoutton = new javax.swing.JButton();
        PartagerBoutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dessin Graphes");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dessin Graphes");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/pic1.jpg"))); // NOI18N

        NouveauGrapheBoutton.setText("Nouveau Graphe");
        NouveauGrapheBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NouveauGrapheBouttonActionPerformed(evt);
            }
        });

        RevenirMesGraphesBoutton.setText("Revenir à mon graphe");

        MesGraphesBoutton.setText("Mes Graphes");

        PartagerBoutton.setText("Partager un graphe");
        PartagerBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartagerBouttonActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(249, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Les membres du groupe (Elie, Léo et Imad) sont les \nseuls personnes privilégiés à modifier ce \nprogramme sur le \"GIT\" par contre vous pouvez \nl'essayer et nous donner vos points de vues.\n(Version 1.0)");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PartagerBoutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MesGraphesBoutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NouveauGrapheBoutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RevenirMesGraphesBoutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NouveauGrapheBoutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MesGraphesBoutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RevenirMesGraphesBoutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PartagerBoutton)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*le test "if (evt.getSource() == NouveauGrapheBoutton)" n'est pas forcément util mais il nous assure
     la bonne fonctionnalité de notre interface en utilisant le ActionEvent de notre API "awt" */
    private void NouveauGrapheBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NouveauGrapheBouttonActionPerformed
       if (evt.getSource() == NouveauGrapheBoutton){        
           dessiner = new DessinerFrame();
           dessiner.setVisible(true);
           NouvGrapheFrame nouvFrame = new NouvGrapheFrame();
           nouvFrame.setVisible(true);    
       }
    }//GEN-LAST:event_NouveauGrapheBouttonActionPerformed

    /*on crée içi un JDialog et on l'associe au frame et on force que sa position soit relative
     au JFrame en utilisant la méthode "JD.setLocationRelativeTo(DF);"*/
    private void PartagerBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartagerBouttonActionPerformed
        DessinerFrame DF=new DessinerFrame();
        DF.setVisible(true);
        JDialogTest JD=new JDialogTest(DF,true);
        JD.setLocationRelativeTo(DF);
        JD.setVisible(true);
    }//GEN-LAST:event_PartagerBouttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new WelcomeFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MesGraphesBoutton;
    private javax.swing.JButton NouveauGrapheBoutton;
    private javax.swing.JButton PartagerBoutton;
    private javax.swing.JButton RevenirMesGraphesBoutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
